import { createHmac, randomUUID } from 'node:crypto'
import { expect, test } from '@playwright/test'

import { requireCanarySecrets } from '../helpers.js'

const projectRoot = '/api/projects/default'
const storageBucket = process.env.GOLARA_STORAGE_BUCKET ?? 'supadata-default'

const signJWT = (payload: Record<string, unknown>, secret: string) => {
  const encode = (value: object) => Buffer.from(JSON.stringify(value)).toString('base64url')
  const header = encode({ alg: 'HS256', typ: 'JWT' })
  const body = encode(payload)
  const signature = createHmac('sha256', secret).update(`${header}.${body}`).digest('base64url')
  return `${header}.${body}.${signature}`
}

test.describe('Golara Canary data plane', () => {
  test('GraphQL executes against the project database', async ({ request }, testInfo) => {
    requireCanarySecrets(testInfo, ['GOLARA_ANON_KEY'])
    const response = await request.post(`${projectRoot}/graphql/v1`, {
      headers: { apikey: process.env.GOLARA_ANON_KEY as string },
      data: { query: '{ __typename }' },
    })

    expect(response.status(), await response.text()).toBe(200)
    expect(await response.json()).toEqual({ data: { __typename: 'Query' } })
  })

  test('REST performs project-scoped create, read, update, and delete mutations', async ({
    request,
  }) => {
    const serviceRoleKey = process.env.GOLARA_SERVICE_ROLE_KEY!
    const table = `restprobe${Date.now()}`
    const marker = randomUUID()
    const query = async (sql: string) => {
      const response = await request.post('/api/platform/pg-meta/default/query', {
        data: { query: sql },
      })
      expect(response.status(), await response.text()).toBe(200)
    }
    const headers = {
      apikey: serviceRoleKey,
      Prefer: 'return=representation',
    }

    await query(
      `create table public.${table} (id bigint generated by default as identity primary key, marker text not null, state text not null)`
    )
    try {
      const created = await request.post(`${projectRoot}/rest/v1/${table}`, {
        headers,
        data: { marker, state: 'created' },
      })
      expect(created.status(), await created.text()).toBe(201)
      const rows = (await created.json()) as { id: number; marker: string; state: string }[]
      expect(rows).toHaveLength(1)

      const updated = await request.patch(`${projectRoot}/rest/v1/${table}?id=eq.${rows[0].id}`, {
        headers,
        data: { state: 'updated' },
      })
      expect(updated.status(), await updated.text()).toBe(200)
      await expect(updated.json()).resolves.toEqual([
        expect.objectContaining({ marker, state: 'updated' }),
      ])

      const selected = await request.get(`${projectRoot}/rest/v1/${table}?marker=eq.${marker}`, {
        headers,
      })
      expect(selected.status(), await selected.text()).toBe(200)
      await expect(selected.json()).resolves.toEqual([
        expect.objectContaining({ marker, state: 'updated' }),
      ])

      const deleted = await request.delete(`${projectRoot}/rest/v1/${table}?id=eq.${rows[0].id}`, {
        headers,
      })
      expect(deleted.status(), await deleted.text()).toBe(200)
      await expect(deleted.json()).resolves.toHaveLength(1)

      const empty = await request.get(`${projectRoot}/rest/v1/${table}`, { headers })
      expect(empty.status(), await empty.text()).toBe(200)
      await expect(empty.json()).resolves.toEqual([])
    } finally {
      await query(`drop table if exists public.${table}`)
    }
  })

  test('GraphQL enforces PostgreSQL row-level security for authenticated JWTs', async ({
    request,
  }, testInfo) => {
    requireCanarySecrets(testInfo, ['GOLARA_ANON_KEY', 'GOLARA_JWT_SECRET'])
    const anonKey = process.env.GOLARA_ANON_KEY!
    const secret = process.env.GOLARA_JWT_SECRET!
    const table = `rlsprobe${Date.now()}`
    const owner = randomUUID()
    const otherOwner = randomUUID()
    const ownedMarker = randomUUID()
    const otherMarker = randomUUID()
    const query = async (sql: string) => {
      const response = await request.post('/api/platform/pg-meta/default/query', {
        data: { query: sql },
      })
      expect(response.status(), await response.text()).toBe(200)
    }

    await query(
      `create table public.${table} (id bigint generated by default as identity primary key, owner text not null, marker text not null)`
    )
    try {
      await query(`alter table public.${table} enable row level security`)
      await query(`grant usage on schema public to authenticated`)
      await query(`grant select on public.${table} to authenticated`)
      await query(
        `create policy ${table}_owner on public.${table} for select to authenticated using (owner = current_setting('request.jwt.claim.sub', true))`
      )
      await query(
        `insert into public.${table} (owner, marker) values ('${owner}', '${ownedMarker}'), ('${otherOwner}', '${otherMarker}')`
      )
      const token = signJWT(
        {
          sub: owner,
          role: 'authenticated',
          aud: 'authenticated',
          iss: process.env.GOLARA_AUTH_ISSUER ?? 'https://supabase.craftmatrix.org/auth/v1',
          project_id: 'default',
          exp: Math.floor(Date.now() / 1000) + 600,
        },
        secret
      )
      type GraphQLPayload = {
        data?: Record<string, { edges: { node: { owner: string; marker: string } }[] }>
        errors?: unknown[]
      }
      let payload: GraphQLPayload = {}
      await expect
        .poll(
          async () => {
            const response = await request.post(`${projectRoot}/graphql/v1`, {
              headers: { apikey: anonKey, Authorization: `Bearer ${token}` },
              data: {
                query: `query { ${table}Collection { edges { node { owner marker } } } }`,
              },
            })
            expect(response.status(), await response.text()).toBe(200)
            payload = (await response.json()) as GraphQLPayload
            return JSON.stringify(payload.errors ?? [])
          },
          { timeout: 30_000 }
        )
        .toBe('[]')
      expect(payload.errors).toBeUndefined()
      expect(payload.data?.[`${table}Collection`].edges).toEqual([
        { node: { owner, marker: ownedMarker } },
      ])
    } finally {
      await query(`drop table if exists public.${table}`)
    }
  })

  test('storage uploads, downloads, lists, and deletes an isolated object', async ({
    request,
  }, testInfo) => {
    requireCanarySecrets(testInfo, ['GOLARA_ANON_KEY', 'GOLARA_SERVICE_ROLE_KEY'])
    const anonKey = process.env.GOLARA_ANON_KEY as string
    const serviceRoleKey = process.env.GOLARA_SERVICE_ROLE_KEY as string
    const objectKey = `e2e/${randomUUID()}.txt`
    const objectPath = `${projectRoot}/storage/v1/object/${storageBucket}/${objectKey}`
    const content = `golara-canary-${randomUUID()}`

    const upload = await request.post(objectPath, {
      headers: { apikey: serviceRoleKey, 'content-type': 'text/plain' },
      data: content,
    })
    expect(upload.status(), await upload.text()).toBe(200)

    try {
      const download = await request.get(objectPath, { headers: { apikey: anonKey } })
      expect(download.status(), await download.text()).toBe(200)
      expect(await download.text()).toBe(content)
      expect(download.headers()['content-type']).toContain('text/plain')

      const list = await request.post(`${projectRoot}/storage/v1/object/list/${storageBucket}`, {
        headers: { apikey: anonKey },
        data: { prefix: 'e2e/', limit: 100, offset: 0 },
      })
      expect(list.status(), await list.text()).toBe(200)
      expect(await list.json()).toEqual(
        expect.arrayContaining([expect.objectContaining({ name: objectKey })])
      )
    } finally {
      const cleanup = await request.delete(objectPath, {
        headers: { apikey: serviceRoleKey },
      })
      expect(cleanup.status(), await cleanup.text()).toBe(200)
    }
  })

  test('anonymous storage mutation is rejected', async ({ request }, testInfo) => {
    requireCanarySecrets(testInfo, ['GOLARA_ANON_KEY'])
    const response = await request.post(
      `${projectRoot}/storage/v1/object/${storageBucket}/denied.txt`,
      {
        headers: { apikey: process.env.GOLARA_ANON_KEY as string },
        data: 'denied',
      }
    )
    expect(response.status()).toBe(401)
  })

  test('CORS preflight declares supported methods and headers', async ({ request }) => {
    const response = await request.fetch(`${projectRoot}/auth/v1/settings`, {
      method: 'OPTIONS',
      headers: {
        Origin: 'https://client.example.invalid',
        'Access-Control-Request-Method': 'GET',
        'Access-Control-Request-Headers': 'apikey,authorization',
      },
    })

    expect(response.status()).toBe(204)
    expect(response.headers()['access-control-allow-methods']).toContain('GET')
    expect(response.headers()['access-control-allow-headers']).toContain('apikey')
  })

  test('Realtime broadcasts between two project-scoped websocket clients', async ({ page }) => {
    const anonKey = process.env.GOLARA_ANON_KEY!
    await page.goto('/project/default')
    const received = await page.evaluate(
      async ({ anonKey }) => {
        const endpoint = `${location.origin.replace(/^http/, 'ws')}/api/projects/default/realtime/v1/websocket?apikey=${encodeURIComponent(anonKey)}&vsn=1.0.0`
        const connect = () =>
          new Promise<WebSocket>((resolve, reject) => {
            const socket = new WebSocket(endpoint)
            socket.addEventListener('open', () => resolve(socket), { once: true })
            socket.addEventListener(
              'error',
              () => reject(new Error('websocket connection failed')),
              {
                once: true,
              }
            )
          })
        const nextMessage = (socket: WebSocket) =>
          new Promise<unknown[]>((resolve, reject) => {
            const timer = setTimeout(() => reject(new Error('websocket message timeout')), 10_000)
            socket.addEventListener(
              'message',
              (event) => {
                clearTimeout(timer)
                resolve(JSON.parse(String(event.data)))
              },
              { once: true }
            )
          })
        const first = await connect()
        const second = await connect()
        try {
          const topic = 'realtime:public:e2e-room'
          first.send(JSON.stringify([null, '1', topic, 'phx_join', {}]))
          await nextMessage(first)
          second.send(JSON.stringify([null, '2', topic, 'phx_join', {}]))
          await nextMessage(second)
          const broadcast = nextMessage(second)
          first.send(
            JSON.stringify([
              null,
              '3',
              topic,
              'broadcast',
              { event: 'message', payload: { text: 'hello' } },
            ])
          )
          return await broadcast
        } finally {
          first.close()
          second.close()
        }
      },
      { anonKey }
    )

    expect(received[3]).toBe('broadcast')
    expect(received[4]).toEqual({ event: 'message', payload: { text: 'hello' } })
  })

  test('Realtime streams database inserts to a service-role subscription', async ({
    page,
    request,
  }) => {
    const serviceRoleKey = process.env.GOLARA_SERVICE_ROLE_KEY!
    const table = `golara_realtime_probe_${Date.now()}`
    const marker = randomUUID()
    const query = async (sql: string) => {
      const response = await request.post('/api/platform/pg-meta/default/query', {
        data: { query: sql },
      })
      expect(response.status(), await response.text()).toBe(200)
    }

    await query(
      `create table public.${table} (id bigint generated by default as identity primary key, marker text not null)`
    )
    try {
      await page.goto('/project/default')
      const received = await page.evaluate(
        async ({ marker, serviceRoleKey, table }) => {
          const endpoint = `${location.origin.replace(/^http/, 'ws')}/api/projects/default/realtime/v1/websocket?apikey=${encodeURIComponent(serviceRoleKey)}&vsn=1.0.0`
          const socket = await new Promise<WebSocket>((resolve, reject) => {
            const value = new WebSocket(endpoint)
            value.addEventListener('open', () => resolve(value), { once: true })
            value.addEventListener(
              'error',
              () => reject(new Error('websocket connection failed')),
              {
                once: true,
              }
            )
          })
          const nextMessage = () =>
            new Promise<unknown[]>((resolve, reject) => {
              const timer = setTimeout(() => reject(new Error('database change timeout')), 10_000)
              socket.addEventListener(
                'message',
                (event) => {
                  clearTimeout(timer)
                  resolve(JSON.parse(String(event.data)))
                },
                { once: true }
              )
            })
          try {
            const topic = `realtime:public:${table}`
            socket.send(
              JSON.stringify([
                null,
                '1',
                topic,
                'phx_join',
                {
                  config: {
                    postgres_changes: [{ event: 'INSERT', schema: 'public', table }],
                  },
                },
              ])
            )
            const joined = await nextMessage()
            if ((joined[4] as { status?: string }).status !== 'ok') {
              throw new Error(`postgres subscription rejected: ${JSON.stringify(joined)}`)
            }
            const pending = nextMessage()
            const inserted = await fetch(
              `/api/projects/default/rest/v1/${encodeURIComponent(table)}`,
              {
                method: 'POST',
                headers: {
                  apikey: serviceRoleKey,
                  'Content-Type': 'application/json',
                  Prefer: 'return=representation',
                },
                body: JSON.stringify({ marker }),
              }
            )
            if (!inserted.ok) throw new Error(`insert failed: ${inserted.status}`)
            return await pending
          } finally {
            socket.close()
          }
        },
        { marker, serviceRoleKey, table }
      )
      expect(received[3]).toBe('postgres_changes')
      expect(received[4]).toMatchObject({ data: { type: 'INSERT', record: { marker } } })
    } finally {
      await query(`drop table if exists public.${table}`)
    }
  })

  test('Edge Function deploys, executes in Deno, lists, and deletes', async ({ request }) => {
    const serviceRoleKey = process.env.GOLARA_SERVICE_ROLE_KEY!
    const slug = `e2e-${Date.now()}`
    const source = `Deno.serve(async (request) => {
  const payload = await request.json()
  return Response.json({ message: \`Hello \${payload.name}\`, runtime: 'deno' }, { status: 201 })
})\n`

    try {
      const deployed = await request.post(
        `/api/v1/projects/default/functions/deploy?slug=${slug}`,
        {
          multipart: {
            metadata: JSON.stringify({ entrypoint_path: 'index.ts', verify_jwt: false }),
            file: { name: 'index.ts', mimeType: 'text/plain', buffer: Buffer.from(source) },
          },
        }
      )
      expect(deployed.status()).toBe(201)
      await expect(deployed.json()).resolves.toMatchObject({ slug, status: 'ACTIVE', version: 1 })

      const listed = await request.get('/api/v1/projects/default/functions')
      expect(listed.status()).toBe(200)
      expect((await listed.json()).some((item: { slug: string }) => item.slug === slug)).toBe(true)

      const invoked = await request.post(`/api/projects/default/functions/v1/${slug}`, {
        headers: { apikey: serviceRoleKey, 'content-type': 'application/json' },
        data: { name: 'Canary' },
      })
      expect(invoked.status()).toBe(201)
      await expect(invoked.json()).resolves.toEqual({ message: 'Hello Canary', runtime: 'deno' })
    } finally {
      const deleted = await request.delete(`/api/v1/projects/default/functions/${slug}`)
      expect([200, 404]).toContain(deleted.status())
    }
  })

  test('database cron job schedules, executes, and cleans up', async ({ request }) => {
    const suffix = Date.now().toString()
    const table = `golara_e2e_job_${suffix}`
    const job = `golara-e2e-${suffix}`
    let jobId: number | undefined
    const query = async (sql: string) => {
      const response = await request.post('/api/platform/pg-meta/default/query', {
        data: { query: sql },
      })
      expect(response.status(), await response.text()).toBe(200)
      return (await response.json()) as Record<string, unknown>[]
    }

    try {
      await query(`create table public.${table} (ran_at timestamptz not null default now())`)
      const scheduled = await query(
        `select cron.schedule('${job}', '1 second', $$insert into public.${table} default values$$) as jobid`
      )
      jobId = Number(scheduled[0]?.jobid)
      expect(jobId).toBeGreaterThan(0)

      await expect
        .poll(
          async () =>
            Number((await query(`select count(*)::int as count from public.${table}`))[0]?.count),
          {
            timeout: 15_000,
          }
        )
        .toBeGreaterThan(0)
    } finally {
      if (jobId) await query(`select cron.unschedule(${jobId})`)
      await query(`drop table if exists public.${table}`)
    }
  })
})
